config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :lists do
    resources :tasks
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :tasks

  validates :title, presence: true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :list

  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :lists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :update, :show, :destroy, :edit]

  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def create
    current_user.lists.create(list_params)
    redirect_to root_path
  end

  def edit
    @list = List.find(params[:id])
    if @list.user != current_user
      return render plain: 'Not Allowed', status: :forbidden
    end
  end

  def show
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])
    @list.update_attributes(list_params)
    redirect_to root_path
  end

  def destroy
    @list = List.find(params[:id])
    if @list.user != current_user
      return render plain: 'Not Allowed', status: :forbidden
    end
    
    @list.destroy
    redirect_to root_path
  end

  private

  def list_params
    params.require(:list).permit(:title)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @task = Task.new
  end

  def create
    @list = List.find(params[:list_id])
    @task = @list.tasks.create(task_params)
    redirect_to list_path(@list)
  end

  private

  def task_params
    params.require(:task).permit(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <title>Manyspoons</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar header">
      <ul class="nav-list">
        <li class="brand"><%= link_to 'How Many Spoons?', root_path, class: 'navbar-brand', alt: 'Home Page' %></li>
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
        </li>
      <% end %>
    </ul>
</nav>

  <% if notice.present? %>
    <p class="alert alert-info"><%= notice %></p>
  <% end %>
  <% if alert.present? %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>

    <%= yield %>


  </body>
</html>

app/views/lists/_form.html.erb
<div class="row">
  <div class="col">
  </div>
  <div class="box col">
    <br />
    <%= simple_form_for @list do |f| %>
      <%= f.input :title %>
      <%= f.submit 'Create', class: 'btn btn-primary'%>
    <% end %>
    <br />
  </div>
  <div class="col">
  </div>
</div>

app/views/lists/edit.html.erb
<h1>Editing List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<p id="notice"><%= notice %></p>



    <div class="lists" role="main">
      <% @lists.each do |list| %>
      <div class="box">
        <h3><%= link_to list.title, list %></h3>
        <div class="list-buttons">
          <%= link_to 'Delete', list, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn' %>
          <%= link_to 'Edit', edit_list_path(list), class: 'btn' %>
        </div>

        <div>
          <ul class="list-group">
            <% list.tasks.each do |task| %>
              <li class="list-group-item">
                <input class="toggle" type="checkbox" id="checkbox">
                <label for="checkbox"><%= task.title %></label>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
      <% end %>
      <div class="box">
        <h2><%= link_to 'New List', new_list_path %></h2>
    </div>
  </div>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Back', lists_path %>

app/views/lists/show.html.erb
<div class="row">
  <div class="col">
  </div>
  <div class="col box">
    <h2><%= @list.title %></h2>
    <%= link_to 'Edit', edit_list_path(@list), class: 'btn btn-primary' %>
    <%= link_to 'Delete', list_path(@list), class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %>
    <%= link_to 'Back', lists_path, class: 'btn btn-primary' %>
    <%= link_to 'Add new task', new_list_task_path(@list), class: 'btn btn-primary' %>
    
  </div>
  <div class="col">
  </div>
</div>

app/views/static_pages/index.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-3">Welcome to How Many Spoons!</h1>
    <p class="lead">We're here to help you get on with getting on.</p>
  </div>
</div>

app/views/tasks/_form.html.erb
<%= simple_form_for @task, url: list_tasks_path(@list) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tasks</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', lists_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>